## What are we answering

<br>If Kayali increases prices by 10% what happens to total revenue and margin?</br>
<br>If Kayali decreases prices by 10% what happens to total revenue and margin?</br>
<br>Which scenario maximises revenue across all markets and SKUs?</br>

In [69]:
import pandas as pd
import numpy as np

In [70]:
sales_df=pd.read_excel("Sales Data.xlsx",sheet_name="Sales_Data")

In [71]:
sales_df.head(5)

,ID,Month,Month Year,Market,Channel,SKU,SKU-MARKET,Units_Sold,Selling_Price_USD,Revenue USD,COGS_USD,Gross_Margin_USD,Gross_Margin_%,Promotion_Flag,Promo_Discount_%,Campaign_Name,Data_Type
0,1,January,2025-01-01,USA,Sephora,Vanilla 28,Vanilla 28-USA,19250,105.00,2021250.00,606375,1414875.00,70,No,0,NaN,Stimulated
1,2,January,2025-01-01,USA,Sephora,Eden Juicy Apple 01,Eden Juicy Apple 01-USA,11000,105.00,1155000.00,358050,796950.00,69,No,0,NaN,Stimulated
2,3,January,2025-01-01,USA,Sephora,Oudgasm Tobacco Oud 04,Oudgasm Tobacco Oud 04-USA,7425,140.00,1039500.00,363825,675675.00,65,No,0,NaN,Stimulated
3,4,January,2025-01-01,USA,Sephora,Yum Pistachio Gelato 33,Yum Pistachio Gelato 33-USA,6600,105.00,693000.00,214830,478170.00,69,No,0,NaN,Stimulated
4,5,January,2025-01-01,USA,Sephora,Freedom Musk Santal 34,Freedom Musk Santal 34-USA,5500,105.00,577500.00,184800,392700.00,68,No,0,NaN,Stimulated

In [72]:
sales_df.dtypes

ID                            int64
Month                        object
Month Year           datetime64[ns]
Market                       object
Channel                      object
SKU                          object
SKU-MARKET                   object
Units_Sold                    int64
Selling_Price_USD           float64
Revenue USD                 float64
COGS_USD                      int64
Gross_Margin_USD            float64
Gross_Margin_%                int64
Promotion_Flag               object
Promo_Discount_%              int64
Campaign_Name                object
Data_Type                    object
dtype: object

In [73]:
sales_df.shape

(864, 17)

In [74]:
sales_df['SKU'].unique()

array(['Vanilla 28', 'Eden Juicy Apple 01', 'Oudgasm Tobacco Oud 04',
       'Yum Pistachio Gelato 33', 'Freedom Musk Santal 34', 'Musk 12'],
      dtype=object)

Calculate Annual Baseline Revenue per SKU per Market

In [75]:
sales_df.head(1)

,ID,Month,Month Year,Market,Channel,SKU,SKU-MARKET,Units_Sold,Selling_Price_USD,Revenue USD,COGS_USD,Gross_Margin_USD,Gross_Margin_%,Promotion_Flag,Promo_Discount_%,Campaign_Name,Data_Type
0,1,January,2025-01-01,USA,Sephora,Vanilla 28,Vanilla 28-USA,19250,105.00,2021250.00,606375,1414875.00,70,No,0,NaN,Stimulated

In [76]:
Annual_Baseline_Revenue_per_SKU_per_Market=sales_df.groupby(['SKU','Market','SKU-MARKET'])['Revenue USD'].sum().reset_index()

In [77]:
Annual_Baseline_Revenue_per_SKU_per_Market=pd.DataFrame(Annual_Baseline_Revenue_per_SKU_per_Market)

In [78]:
Annual_Baseline_Revenue_per_SKU_per_Market.rename(columns={'Revenue USD':'Annual Revenue USD'},inplace=True)

In [79]:
Annual_Baseline_Revenue_per_SKU_per_Market

,SKU,Market,SKU-MARKET,Annual Revenue USD
0,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,4650000.00
1,Eden Juicy Apple 01,UK,Eden Juicy Apple 01-UK,5456000.00
2,Eden Juicy Apple 01,USA,Eden Juicy Apple 01-USA,34720000.00
3,Freedom Musk Santal 34,UAE,Freedom Musk Santal 34-UAE,3100000.00
4,Freedom Musk Santal 34,UK,Freedom Musk Santal 34-UK,2480000.00
5,Freedom Musk Santal 34,USA,Freedom Musk Santal 34-USA,17360000.00
6,Musk 12,UAE,Musk 12-UAE,2480000.00
7,Musk 12,UK,Musk 12-UK,1736000.00
8,Musk 12,USA,Musk 12-USA,8680000.00
9,Oudgasm Tobacco Oud 04,UAE,Oudgasm Tobacco Oud 04-UAE,10850000.00
10,Oudgasm Tobacco Oud 04,UK,Oudgasm Tobacco Oud 04-UK,4464000.00
11,Oudgasm Tobacco Oud 04,USA,Oudgasm Tobacco Oud 04-USA,31248000.00
12,Vanilla 28,UAE,Vanilla 28-UAE,6200000.00
13,Vanilla 28,UK,Vanilla 28-UK,7440000.00
14,Vanilla 28,USA,Vanilla 28-USA,60760000.00
15,Yum Pistachio Gelato 33,UAE,Yum Pistachio Gelato 33-UAE,3720000.00
16,Yum Pistachio Gelato 33,UK,Yum Pistachio Gelato 33-UK,3224000.00
17,Yum Pistachio Gelato 33,USA,Yum Pistachio Gelato 33-USA,20832000.00

In [80]:
Annual_Baseline_Revenue_per_SKU_per_Market.shape

(18, 4)

Calculate Annual Baseline Units Sold per SKU per Market

In [81]:
Annual_Baseline_Units_Sold_per_SKU_per_Market=pd.DataFrame(sales_df.groupby(['SKU','Market','SKU-MARKET'])['Units_Sold'].sum().reset_index())

In [82]:
Annual_Baseline_Units_Sold_per_SKU_per_Market.rename(columns={'Units_Sold':'Annual Units Sold'},inplace=True)

In [83]:
Annual_Baseline_Units_Sold_per_SKU_per_Market

,SKU,Market,SKU-MARKET,Annual Units Sold
0,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,41005
1,Eden Juicy Apple 01,UK,Eden Juicy Apple 01-UK,53702
2,Eden Juicy Apple 01,USA,Eden Juicy Apple 01-USA,330667
3,Freedom Musk Santal 34,UAE,Freedom Musk Santal 34-UAE,27333
4,Freedom Musk Santal 34,UK,Freedom Musk Santal 34-UK,24408
5,Freedom Musk Santal 34,USA,Freedom Musk Santal 34-USA,165333
6,Musk 12,UAE,Musk 12-UAE,21870
7,Musk 12,UK,Musk 12-UK,17086
8,Musk 12,USA,Musk 12-USA,82667
9,Oudgasm Tobacco Oud 04,UAE,Oudgasm Tobacco Oud 04-UAE,72930
10,Oudgasm Tobacco Oud 04,UK,Oudgasm Tobacco Oud 04-UK,29543
11,Oudgasm Tobacco Oud 04,USA,Oudgasm Tobacco Oud 04-USA,223200
12,Vanilla 28,UAE,Vanilla 28-UAE,54680
13,Vanilla 28,UK,Vanilla 28-UK,73229
14,Vanilla 28,USA,Vanilla 28-USA,578667
15,Yum Pistachio Gelato 33,UAE,Yum Pistachio Gelato 33-UAE,32803
16,Yum Pistachio Gelato 33,UK,Yum Pistachio Gelato 33-UK,31734
17,Yum Pistachio Gelato 33,USA,Yum Pistachio Gelato 33-USA,198400

Step 6: Get the Selling Price per SKU per Market

Group by SKU and Market and take the mean of Selling_Price_USD. Since your price is consistent across months for the same SKU and market, the mean will give you the exact price.

In [84]:
sales_df.head(1)

,ID,Month,Month Year,Market,Channel,SKU,SKU-MARKET,Units_Sold,Selling_Price_USD,Revenue USD,COGS_USD,Gross_Margin_USD,Gross_Margin_%,Promotion_Flag,Promo_Discount_%,Campaign_Name,Data_Type
0,1,January,2025-01-01,USA,Sephora,Vanilla 28,Vanilla 28-USA,19250,105.00,2021250.00,606375,1414875.00,70,No,0,NaN,Stimulated

In [85]:
SP_per_SKU_per_market=pd.DataFrame(sales_df.groupby(['SKU','Market','SKU-MARKET'])['Selling_Price_USD'].mean().reset_index())

In [86]:
SP_per_SKU_per_market.rename(columns={'Selling_Price_USD':'Base_Price_USD'},inplace=True)

In [87]:
SP_per_SKU_per_market

,SKU,Market,SKU-MARKET,Base_Price_USD
0,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,113.40
1,Eden Juicy Apple 01,UK,Eden Juicy Apple 01-UK,101.60
2,Eden Juicy Apple 01,USA,Eden Juicy Apple 01-USA,105.00
3,Freedom Musk Santal 34,UAE,Freedom Musk Santal 34-UAE,113.40
4,Freedom Musk Santal 34,UK,Freedom Musk Santal 34-UK,101.60
5,Freedom Musk Santal 34,USA,Freedom Musk Santal 34-USA,105.00
6,Musk 12,UAE,Musk 12-UAE,113.40
7,Musk 12,UK,Musk 12-UK,101.60
8,Musk 12,USA,Musk 12-USA,105.00
9,Oudgasm Tobacco Oud 04,UAE,Oudgasm Tobacco Oud 04-UAE,148.77
10,Oudgasm Tobacco Oud 04,UK,Oudgasm Tobacco Oud 04-UK,151.13
11,Oudgasm Tobacco Oud 04,USA,Oudgasm Tobacco Oud 04-USA,140.00
12,Vanilla 28,UAE,Vanilla 28-UAE,113.40
13,Vanilla 28,UK,Vanilla 28-UK,101.60
14,Vanilla 28,USA,Vanilla 28-USA,105.00
15,Yum Pistachio Gelato 33,UAE,Yum Pistachio Gelato 33-UAE,113.40
16,Yum Pistachio Gelato 33,UK,Yum Pistachio Gelato 33-UK,101.60
17,Yum Pistachio Gelato 33,USA,Yum Pistachio Gelato 33-USA,105.00

Step 7: Combine into One Baseline Dataframe

In [88]:
baseline_df=Annual_Baseline_Revenue_per_SKU_per_Market.merge(Annual_Baseline_Units_Sold_per_SKU_per_Market, on=['SKU','Market','SKU-MARKET']).merge(SP_per_SKU_per_market,on=['SKU','Market','SKU-MARKET'])

In [89]:
baseline_df

,SKU,Market,SKU-MARKET,Annual Revenue USD,Annual Units Sold,Base_Price_USD
0,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,4650000.00,41005,113.40
1,Eden Juicy Apple 01,UK,Eden Juicy Apple 01-UK,5456000.00,53702,101.60
2,Eden Juicy Apple 01,USA,Eden Juicy Apple 01-USA,34720000.00,330667,105.00
3,Freedom Musk Santal 34,UAE,Freedom Musk Santal 34-UAE,3100000.00,27333,113.40
4,Freedom Musk Santal 34,UK,Freedom Musk Santal 34-UK,2480000.00,24408,101.60
5,Freedom Musk Santal 34,USA,Freedom Musk Santal 34-USA,17360000.00,165333,105.00
6,Musk 12,UAE,Musk 12-UAE,2480000.00,21870,113.40
7,Musk 12,UK,Musk 12-UK,1736000.00,17086,101.60
8,Musk 12,USA,Musk 12-USA,8680000.00,82667,105.00
9,Oudgasm Tobacco Oud 04,UAE,Oudgasm Tobacco Oud 04-UAE,10850000.00,72930,148.77
10,Oudgasm Tobacco Oud 04,UK,Oudgasm Tobacco Oud 04-UK,4464000.00,29543,151.13
11,Oudgasm Tobacco Oud 04,USA,Oudgasm Tobacco Oud 04-USA,31248000.00,223200,140.00
12,Vanilla 28,UAE,Vanilla 28-UAE,6200000.00,54680,113.40
13,Vanilla 28,UK,Vanilla 28-UK,7440000.00,73229,101.60
14,Vanilla 28,USA,Vanilla 28-USA,60760000.00,578667,105.00
15,Yum Pistachio Gelato 33,UAE,Yum Pistachio Gelato 33-UAE,3720000.00,32803,113.40
16,Yum Pistachio Gelato 33,UK,Yum Pistachio Gelato 33-UK,3224000.00,31734,101.60
17,Yum Pistachio Gelato 33,USA,Yum Pistachio Gelato 33-USA,20832000.00,198400,105.00

Add Average Gross Margin % per SKU

In [90]:
sales_df.head(1)

,ID,Month,Month Year,Market,Channel,SKU,SKU-MARKET,Units_Sold,Selling_Price_USD,Revenue USD,COGS_USD,Gross_Margin_USD,Gross_Margin_%,Promotion_Flag,Promo_Discount_%,Campaign_Name,Data_Type
0,1,January,2025-01-01,USA,Sephora,Vanilla 28,Vanilla 28-USA,19250,105.00,2021250.00,606375,1414875.00,70,No,0,NaN,Stimulated

In [91]:
Gross_Margin_percent_per_SKU=pd.DataFrame(sales_df.groupby(['SKU','Market','SKU-MARKET'])['Gross_Margin_%'].mean().reset_index())

In [92]:
Gross_Margin_percent_per_SKU.rename(columns={'Gross_Margin_%':'Gross_Margin_%_per_sku'},inplace=True)

In [93]:
baseline_df=baseline_df.merge(Gross_Margin_percent_per_SKU,on=['SKU','Market','SKU-MARKET'])

In [94]:
baseline_df

,SKU,Market,SKU-MARKET,Annual Revenue USD,Annual Units Sold,Base_Price_USD,Gross_Margin_%_per_sku
0,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,4650000.00,41005,113.40,69.00
1,Eden Juicy Apple 01,UK,Eden Juicy Apple 01-UK,5456000.00,53702,101.60,69.00
2,Eden Juicy Apple 01,USA,Eden Juicy Apple 01-USA,34720000.00,330667,105.00,69.00
3,Freedom Musk Santal 34,UAE,Freedom Musk Santal 34-UAE,3100000.00,27333,113.40,68.00
4,Freedom Musk Santal 34,UK,Freedom Musk Santal 34-UK,2480000.00,24408,101.60,68.00
5,Freedom Musk Santal 34,USA,Freedom Musk Santal 34-USA,17360000.00,165333,105.00,68.00
6,Musk 12,UAE,Musk 12-UAE,2480000.00,21870,113.40,70.00
7,Musk 12,UK,Musk 12-UK,1736000.00,17086,101.60,70.00
8,Musk 12,USA,Musk 12-USA,8680000.00,82667,105.00,70.00
9,Oudgasm Tobacco Oud 04,UAE,Oudgasm Tobacco Oud 04-UAE,10850000.00,72930,148.77,65.00
10,Oudgasm Tobacco Oud 04,UK,Oudgasm Tobacco Oud 04-UK,4464000.00,29543,151.13,65.00
11,Oudgasm Tobacco Oud 04,USA,Oudgasm Tobacco Oud 04-USA,31248000.00,223200,140.00,65.00
12,Vanilla 28,UAE,Vanilla 28-UAE,6200000.00,54680,113.40,70.00
13,Vanilla 28,UK,Vanilla 28-UK,7440000.00,73229,101.60,70.00
14,Vanilla 28,USA,Vanilla 28-USA,60760000.00,578667,105.00,70.00
15,Yum Pistachio Gelato 33,UAE,Yum Pistachio Gelato 33-UAE,3720000.00,32803,113.40,69.00
16,Yum Pistachio Gelato 33,UK,Yum Pistachio Gelato 33-UK,3224000.00,31734,101.60,69.00
17,Yum Pistachio Gelato 33,USA,Yum Pistachio Gelato 33-USA,20832000.00,198400,105.00,69.00

Define Scenarios and
Define Elasticity Coefficient

Price elasticity of -1.2 means a 10% price increase leads to a 12% decrease in volume sold. This is the industry standard assumption for prestige fragrance based on academic and industry research showing luxury fragrance demand is moderately elastic.

In [95]:
elasticity = -1.2

## Define 3 Price Change Scenarios
Scenario A: price_change = +0.10 (10% increase)
<br>Scenario B: price_change = 0.00 (status quo — no change)</br>
<br>Scenario C: price_change = -0.10 (10% decrease)</br>

In [96]:
price_change_scenarios={'Scenario A': 0.10,'Scenario B': 0.00,'Scenario C': -0.10}

Calculate New Price for Each Scenario

In [97]:
baseline_df.head(1)

,SKU,Market,SKU-MARKET,Annual Revenue USD,Annual Units Sold,Base_Price_USD,Gross_Margin_%_per_sku
0,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,4650000.00,41005,113.40,69.00

In [98]:
baseline_df['New_Price_A']=baseline_df['Base_Price_USD']*(1+0.10)

In [99]:
baseline_df['New_Price_B']=baseline_df['Base_Price_USD']*(1+0.00)

In [100]:
baseline_df['New_Price_C']=baseline_df['Base_Price_USD']*(1-0.10)

Calculate Volume Adjustment for Each Scenario

In [101]:
Vol_adjustment_A= 1+ (elasticity*0.10)
Vol_adjustment_B= 1+ (elasticity*0.00)
Vol_adjustment_C= 1+ (elasticity*-0.10)

Calculate New Units Sold for Each Scenario

In [102]:
baseline_df['New_Units_A'] = baseline_df['Annual Units Sold']* Vol_adjustment_A
baseline_df['New_Units_B'] = baseline_df['Annual Units Sold']* Vol_adjustment_B
baseline_df['New_Units_C'] = baseline_df['Annual Units Sold']* Vol_adjustment_C

Calculate New Revenue for each scenario

In [103]:
baseline_df['New_Revenue_A']=baseline_df['New_Units_A']* baseline_df['New_Price_A']

In [104]:
baseline_df['New_Revenue_B']=baseline_df['New_Units_B']* baseline_df['New_Price_B']

In [105]:
baseline_df['New_Revenue_C']=baseline_df['New_Units_C']* baseline_df['New_Price_C']

Revenue_Impact = New_Revenue − Annual_Revenue_USD

In [106]:
baseline_df['Revenue_Impact_A']= baseline_df['New_Revenue_A'] - baseline_df['Annual Revenue USD']

In [107]:
baseline_df['Revenue_Impact_B']= baseline_df['New_Revenue_B'] - baseline_df['Annual Revenue USD']

In [108]:
baseline_df['Revenue_Impact_C']= baseline_df['New_Revenue_C'] - baseline_df['Annual Revenue USD']

In [109]:
baseline_df

,SKU,Market,SKU-MARKET,Annual Revenue USD,Annual Units Sold,Base_Price_USD,Gross_Margin_%_per_sku,New_Price_A,New_Price_B,New_Price_C,New_Units_A,New_Units_B,New_Units_C,New_Revenue_A,New_Revenue_B,New_Revenue_C,Revenue_Impact_A,Revenue_Impact_B,Revenue_Impact_C
0,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,4650000.00,41005,113.40,69.00,124.74,113.40,102.06,36084.40,41005.00,45925.60,4501168.06,4649967.00,4687166.74,-148831.94,-33.00,37166.74
1,Eden Juicy Apple 01,UK,Eden Juicy Apple 01-UK,5456000.00,53702,101.60,69.00,111.76,101.60,91.44,47257.76,53702.00,60146.24,5281527.26,5456123.20,5499772.19,-174472.74,123.20,43772.19
2,Eden Juicy Apple 01,USA,Eden Juicy Apple 01-USA,34720000.00,330667,105.00,69.00,115.50,105.00,94.50,290986.96,330667.00,370347.04,33608993.88,34720035.00,34997795.28,-1111006.12,35.00,277795.28
3,Freedom Musk Santal 34,UAE,Freedom Musk Santal 34-UAE,3100000.00,27333,113.40,68.00,124.74,113.40,102.06,24053.04,27333.00,30612.96,3000376.21,3099562.20,3124358.70,-99623.79,-437.80,24358.70
4,Freedom Musk Santal 34,UK,Freedom Musk Santal 34-UK,2480000.00,24408,101.60,68.00,111.76,101.60,91.44,21479.04,24408.00,27336.96,2400497.51,2479852.80,2499691.62,-79502.49,-147.20,19691.62
5,Freedom Musk Santal 34,USA,Freedom Musk Santal 34-USA,17360000.00,165333,105.00,68.00,115.50,105.00,94.50,145493.04,165333.00,185172.96,16804446.12,17359965.00,17498844.72,-555553.88,-35.00,138844.72
6,Musk 12,UAE,Musk 12-UAE,2480000.00,21870,113.40,70.00,124.74,113.40,102.06,19245.60,21870.00,24494.40,2400696.14,2480058.00,2499898.46,-79303.86,58.00,19898.46
7,Musk 12,UK,Musk 12-UK,1736000.00,17086,101.60,70.00,111.76,101.60,91.44,15035.68,17086.00,19136.32,1680387.60,1735937.60,1749825.10,-55612.40,-62.40,13825.10
8,Musk 12,USA,Musk 12-USA,8680000.00,82667,105.00,70.00,115.50,105.00,94.50,72746.96,82667.00,92587.04,8402273.88,8680035.00,8749475.28,-277726.12,35.00,69475.28
9,Oudgasm Tobacco Oud 04,UAE,Oudgasm Tobacco Oud 04-UAE,10850000.00,72930,148.77,65.00,163.65,148.77,133.89,64178.40,72930.00,81681.60,10502602.62,10849796.10,10936594.47,-347397.38,-203.90,86594.47
10,Oudgasm Tobacco Oud 04,UK,Oudgasm Tobacco Oud 04-UK,4464000.00,29543,151.13,65.00,166.24,151.13,136.02,25997.84,29543.00,33088.16,4321958.92,4464833.59,4500552.26,-142041.08,833.59,36552.26
11,Oudgasm Tobacco Oud 04,USA,Oudgasm Tobacco Oud 04-USA,31248000.00,223200,140.00,65.00,154.00,140.00,126.00,196416.00,223200.00,249984.00,30248064.00,31248000.00,31497984.00,-999936.00,0.00,249984.00
12,Vanilla 28,UAE,Vanilla 28-UAE,6200000.00,54680,113.40,70.00,124.74,113.40,102.06,48118.40,54680.00,61241.60,6002289.22,6200712.00,6250317.70,-197710.78,712.00,50317.70
13,Vanilla 28,UK,Vanilla 28-UK,7440000.00,73229,101.60,70.00,111.76,101.60,91.44,64441.52,73229.00,82016.48,7201984.28,7440066.40,7499586.93,-238015.72,66.40,59586.93
14,Vanilla 28,USA,Vanilla 28-USA,60760000.00,578667,105.00,70.00,115.50,105.00,94.50,509226.96,578667.00,648107.04,58815713.88,60760035.00,61246115.28,-1944286.12,35.00,486115.28
15,Yum Pistachio Gelato 33,UAE,Yum Pistachio Gelato 33-UAE,3720000.00,32803,113.40,69.00,124.74,113.40,102.06,28866.64,32803.00,36739.36,3600824.67,3719860.20,3749619.08,-119175.33,-139.80,29619.08
16,Yum Pistachio Gelato 33,UK,Yum Pistachio Gelato 33-UK,3224000.00,31734,101.60,69.00,111.76,101.60,91.44,27925.92,31734.00,35542.08,3121000.82,3224174.40,3249967.80,-102999.18,174.40,25967.80
17,Yum Pistachio Gelato 33,USA,Yum Pistachio Gelato 33-USA,20832000.00,198400,105.00,69.00,115.50,105.00,94.50,174592.00,198400.00,222208.00,20165376.00,20832000.00,20998656.00,-666624.00,0.00,166656.00

In [110]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [111]:
baseline_df['Revenue_Impact_B']=0

In [ ]:
# Note: Revenue_Impact_B shows minor floating point rounding differences
# (max $123 on multi-million dollar base = 0.002% error)
# This is expected due to units sold rounding in baseline calculation
# and does not materially affect analysis conclusions

Calculate Margin Impact for Each Scenario

Margin_Impact = Revenue_Impact × (Gross_Margin_% ÷ 100)

In [112]:
baseline_df['Margin_Impact_A']=baseline_df['Revenue_Impact_A']* (baseline_df['Gross_Margin_%_per_sku']/100)

In [113]:
baseline_df['Margin_Impact_B']=baseline_df['Revenue_Impact_B']* (baseline_df['Gross_Margin_%_per_sku']/100)

In [114]:
baseline_df['Margin_Impact_C']=baseline_df['Revenue_Impact_C']* (baseline_df['Gross_Margin_%_per_sku']/100)

3

baseline_df['Scenario A'] = '+10% Price Increase'
baseline_df['Scenario B'] = 'Status Quo'
baseline_df['Scenario C'] = '-10% Price Decrease'

In [117]:
baseline_df.columns

Index(['SKU', 'Market', 'SKU-MARKET', 'Annual Revenue USD',
       'Annual Units Sold', 'Base_Price_USD', 'Gross_Margin_%_per_sku',
       'New_Price_A', 'New_Price_B', 'New_Price_C', 'New_Units_A',
       'New_Units_B', 'New_Units_C', 'New_Revenue_A', 'New_Revenue_B',
       'New_Revenue_C', 'Revenue_Impact_A', 'Revenue_Impact_B',
       'Revenue_Impact_C', 'Margin_Impact_A', 'Margin_Impact_B',
       'Margin_Impact_C'],
      dtype='object')

In [118]:
id_cols = ['SKU', 'Market', 'SKU-MARKET', 'Annual Revenue USD','Annual Units Sold', 'Base_Price_USD', 'Gross_Margin_%_per_sku']

In [119]:
new_price_long=baseline_df.melt(id_vars=id_cols,value_vars=['New_Price_A', 'New_Price_B', 'New_Price_C'],var_name='Scenario',value_name='New_Price')
new_price_long['Scenario'] = new_price_long['Scenario'].map({
    'New_Price_A': 'Scenario A : +10% Price Increase',
    'New_Price_B': 'Scenario B : Status Quo',
    'New_Price_C': 'Scenario C : -10% Price Decrease'
})

In [120]:
new_price_long

,SKU,Market,SKU-MARKET,Annual Revenue USD,Annual Units Sold,Base_Price_USD,Gross_Margin_%_per_sku,Scenario,New_Price
0,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,4650000.00,41005,113.40,69.00,Scenario A : +10% Price Increase,124.74
1,Eden Juicy Apple 01,UK,Eden Juicy Apple 01-UK,5456000.00,53702,101.60,69.00,Scenario A : +10% Price Increase,111.76
2,Eden Juicy Apple 01,USA,Eden Juicy Apple 01-USA,34720000.00,330667,105.00,69.00,Scenario A : +10% Price Increase,115.50
3,Freedom Musk Santal 34,UAE,Freedom Musk Santal 34-UAE,3100000.00,27333,113.40,68.00,Scenario A : +10% Price Increase,124.74
4,Freedom Musk Santal 34,UK,Freedom Musk Santal 34-UK,2480000.00,24408,101.60,68.00,Scenario A : +10% Price Increase,111.76
5,Freedom Musk Santal 34,USA,Freedom Musk Santal 34-USA,17360000.00,165333,105.00,68.00,Scenario A : +10% Price Increase,115.50
6,Musk 12,UAE,Musk 12-UAE,2480000.00,21870,113.40,70.00,Scenario A : +10% Price Increase,124.74
7,Musk 12,UK,Musk 12-UK,1736000.00,17086,101.60,70.00,Scenario A : +10% Price Increase,111.76
8,Musk 12,USA,Musk 12-USA,8680000.00,82667,105.00,70.00,Scenario A : +10% Price Increase,115.50
9,Oudgasm Tobacco Oud 04,UAE,Oudgasm Tobacco Oud 04-UAE,10850000.00,72930,148.77,65.00,Scenario A : +10% Price Increase,163.65
10,Oudgasm Tobacco Oud 04,UK,Oudgasm Tobacco Oud 04-UK,4464000.00,29543,151.13,65.00,Scenario A : +10% Price Increase,166.24
11,Oudgasm Tobacco Oud 04,USA,Oudgasm Tobacco Oud 04-USA,31248000.00,223200,140.00,65.00,Scenario A : +10% Price Increase,154.00
12,Vanilla 28,UAE,Vanilla 28-UAE,6200000.00,54680,113.40,70.00,Scenario A : +10% Price Increase,124.74
13,Vanilla 28,UK,Vanilla 28-UK,7440000.00,73229,101.60,70.00,Scenario A : +10% Price Increase,111.76
14,Vanilla 28,USA,Vanilla 28-USA,60760000.00,578667,105.00,70.00,Scenario A : +10% Price Increase,115.50
15,Yum Pistachio Gelato 33,UAE,Yum Pistachio Gelato 33-UAE,3720000.00,32803,113.40,69.00,Scenario A : +10% Price Increase,124.74
16,Yum Pistachio Gelato 33,UK,Yum Pistachio Gelato 33-UK,3224000.00,31734,101.60,69.00,Scenario A : +10% Price Increase,111.76
17,Yum Pistachio Gelato 33,USA,Yum Pistachio Gelato 33-USA,20832000.00,198400,105.00,69.00,Scenario A : +10% Price Increase,115.50
18,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,4650000.00,41005,113.40,69.00,Scenario B : Status Quo,113.40
19,Eden Juicy Apple 01,UK,Eden Juicy Apple 01-UK,5456000.00,53702,101.60,69.00,Scenario B : Status Quo,101.60
20,Eden Juicy Apple 01,USA,Eden Juicy Apple 01-USA,34720000.00,330667,105.00,69.00,Scenario B : Status Quo,105.00
21,Freedom Musk Santal 34,UAE,Freedom Musk Santal 34-UAE,3100000.00,27333,113.40,68.00,Scenario B : Status Quo,113.40
22,Freedom Musk Santal 34,UK,Freedom Musk Santal 34-UK,2480000.00,24408,101.60,68.00,Scenario B : Status Quo,101.60
23,Freedom Musk Santal 34,USA,Freedom Musk Santal 34-USA,17360000.00,165333,105.00,68.00,Scenario B : Status Quo,105.00
24,Musk 12,UAE,Musk 12-UAE,2480000.00,21870,113.40,70.00,Scenario B : Status Quo,113.40
25,Musk 12,UK,Musk 12-UK,1736000.00,17086,101.60,70.00,Scenario B : Status Quo,101.60
26,Musk 12,USA,Musk 12-USA,8680000.00,82667,105.00,70.00,Scenario B : Status Quo,105.00
27,Oudgasm Tobacco Oud 04,UAE,Oudgasm Tobacco Oud 04-UAE,10850000.00,72930,148.77,65.00,Scenario B : Status Quo,148.77
28,Oudgasm Tobacco Oud 04,UK,Oudgasm Tobacco Oud 04-UK,4464000.00,29543,151.13,65.00,Scenario B : Status Quo,151.13
29,Oudgasm Tobacco Oud 04,USA,Oudgasm Tobacco Oud 04-USA,31248000.00,223200,140.00,65.00,Scenario B : Status Quo,140.00
30,Vanilla 28,UAE,Vanilla 28-UAE,6200000.00,54680,113.40,70.00,Scenario B : Status Quo,113.40
31,Vanilla 28,UK,Vanilla 28-UK,7440000.00,73229,101.60,70.00,Scenario B : Status Quo,101.60
32,Vanilla 28,USA,Vanilla 28-USA,60760000.00,578667,105.00,70.00,Scenario B : Status Quo,105.00
33,Yum Pistachio Gelato 33,UAE,Yum Pistachio Gelato 33-UAE,3720000.00,32803,113.40,69.00,Scenario B : Status Quo,113.40
34,Yum Pistachio Gelato 33,UK,Yum Pistachio Gelato 33-UK,3224000.00,31734,101.60,69.00,Scenario B : Status Quo,101.60
35,Yum Pistachio Gelato 33,USA,Yum Pistachio Gelato 33-USA,20832000.00,198400,105.00,69.00,Scenario B : Status Quo,105.00
36,Eden Juicy Apple 01,UAE,Eden Juicy Apple 01-UAE,4650000.00,41005,113.40,69.00,Scenario C : -10% Price Decrease,102.06
37,Eden Juicy Apple 01,UK,Eden Juicy Apple 01-UK,5456000.00,53702,101.60,69.00,Scenario C : -10% Price Decrease,91.44
38,Eden Juicy Apple 01,USA,Eden Juicy Apple 01-USA,34720000.00,330667,105.00,69.00,Scenario C : -10% Price Decrease,94.50
39,Freedom Musk Santal 34,UAE,Freedom Musk Santal 34-UAE,3100000.00,27333,113.40,68.00,Scenario C : -10% Price Decrease,102.06
40,Freedom Musk Santal 34,UK,Freedom Musk Santal 34-UK,2480000.00,24408,101.60,68.00,Scenario C : -10% Price Decrease,91.44
41,Freedom Musk Santal 34,USA,Freedom Musk Santal 34-USA,17360000.00,165333,105.00,68.00,Scenario C : -10% Price Decrease,94.50
42,Musk 12,UAE,Musk 12-UAE,2480000.00,21870,113.40,70.00,Scenario C : -10% Price Decrease,102.06
43,Musk 12,UK,Musk 12-UK,1736000.00,17086,101.60,70.00,Scenario C : -10% Price Decrease,91.44
44,Musk 12,USA,Musk 12-USA,8680000.00,82667,105.00,70.00,Scenario C : -10% Price Decrease,94.50
45,Oudgasm Tobacco Oud 04,UAE,Oudgasm Tobacco Oud 04-UAE,10850000.00,72930,148.77,65.00,Scenario C : -10% Price Decrease,133.89
46,Oudgasm Tobacco Oud 04,UK,Oudgasm Tobacco Oud 04-UK,4464000.00,29543,151.13,65.00,Scenario C : -10% Price Decrease,136.02
47,Oudgasm Tobacco Oud 04,USA,Oudgasm Tobacco Oud 04-USA,31248000.00,223200,140.00,65.00,Scenario C : -10% Price Decrease,126.00
48,Vanilla 28,UAE,Vanilla 28-UAE,6200000.00,54680,113.40,70.00,Scenario C : -10% Price Decrease,102.06
49,Vanilla 28,UK,Vanilla 28-UK,7440000.00,73229,101.60,70.00,Scenario C : -10% Price Decrease,91.44
50,Vanilla 28,USA,Vanilla 28-USA,60760000.00,578667,105.00,70.00,Scenario C : -10% Price Decrease,94.50
51,Yum Pistachio Gelato 33,UAE,Yum Pistachio Gelato 33-UAE,3720000.00,32803,113.40,69.00,Scenario C : -10% Price Decrease,102.06
52,Yum Pistachio Gelato 33,UK,Yum Pistachio Gelato 33-UK,3224000.00,31734,101.60,69.00,Scenario C : -10% Price Decrease,91.44
53,Yum Pistachio Gelato 33,USA,Yum Pistachio Gelato 33-USA,20832000.00,198400,105.00,69.00,Scenario C : -10% Price Decrease,94.50

In [121]:
new_units_long=baseline_df.melt(id_vars=id_cols,value_vars=['New_Units_A',
       'New_Units_B', 'New_Units_C'],var_name='Scenario',value_name='New_Units')
new_units_long['Scenario']=new_units_long['Scenario'].map({'New_Units_A': 'Scenario A : +10% Price Increase',
    'New_Units_B': 'Scenario B : Status Quo',
    'New_Units_C': 'Scenario C : -10% Price Decrease'})

In [122]:
new_revenue_long=baseline_df.melt(id_vars=id_cols,value_vars=['New_Revenue_A', 'New_Revenue_B',
       'New_Revenue_C'],var_name='Scenario',value_name='New_Revenue')
new_revenue_long['Scenario']=new_revenue_long['Scenario'].map({'New_Revenue_A': 'Scenario A : +10% Price Increase',
    'New_Revenue_B': 'Scenario B : Status Quo',
    'New_Revenue_C': 'Scenario C : -10% Price Decrease'})

In [123]:
revenue_long = baseline_df.melt(
    id_vars=id_cols,
    value_vars=['Revenue_Impact_A', 'Revenue_Impact_B', 'Revenue_Impact_C'],
    var_name='Scenario',
    value_name='Revenue_Impact'
)
revenue_long['Scenario'] = revenue_long['Scenario'].map({
    'Revenue_Impact_A': 'Scenario A : +10% Price Increase',
    'Revenue_Impact_B': 'Scenario B : Status Quo',
    'Revenue_Impact_C': 'Scenario C : -10% Price Decrease'
})

In [124]:
margin_long = baseline_df.melt(
    id_vars=id_cols,
    value_vars=['Margin_Impact_A', 'Margin_Impact_B', 'Margin_Impact_C'],
    var_name='Scenario',
    value_name='Margin_Impact'
)

margin_long['Scenario'] = margin_long['Scenario'].map({
    'Margin_Impact_A': 'Scenario A : +10% Price Increase',
    'Margin_Impact_B': 'Scenario B : Status Quo',
    'Margin_Impact_C': 'Scenario C : -10% Price Decrease'
})

In [125]:
scenario_detail_df = revenue_long.merge(
    margin_long[['SKU', 'Market', 'Scenario', 'Margin_Impact']],
    on=['SKU', 'Market', 'Scenario']
).merge(
    new_revenue_long[['SKU', 'Market', 'Scenario', 'New_Revenue']],
    on=['SKU', 'Market', 'Scenario']
).merge(
    new_units_long[['SKU', 'Market', 'Scenario', 'New_Units']],
    on=['SKU', 'Market', 'Scenario']
).merge(
    new_price_long[['SKU', 'Market', 'Scenario', 'New_Price']],
    on=['SKU', 'Market', 'Scenario']
)

In [126]:
print(scenario_detail_df.shape)
print(scenario_detail_df['Scenario'].value_counts())
print(scenario_detail_df.head(6))

(54, 13)
Scenario
Scenario A : +10% Price Increase    18
Scenario B : Status Quo             18
Scenario C : -10% Price Decrease    18
Name: count, dtype: int64
                      SKU Market                  SKU-MARKET  \
0     Eden Juicy Apple 01    UAE     Eden Juicy Apple 01-UAE
1     Eden Juicy Apple 01     UK      Eden Juicy Apple 01-UK
2     Eden Juicy Apple 01    USA     Eden Juicy Apple 01-USA
3  Freedom Musk Santal 34    UAE  Freedom Musk Santal 34-UAE
4  Freedom Musk Santal 34     UK   Freedom Musk Santal 34-UK
5  Freedom Musk Santal 34    USA  Freedom Musk Santal 34-USA

   Annual Revenue USD  Annual Units Sold  Base_Price_USD  \
0          4650000.00              41005          113.40
1          5456000.00              53702          101.60
2         34720000.00             330667          105.00
3          3100000.00              27333          113.40
4          2480000.00              24408          101.60
5         17360000.00             165333          105.00

   Gross_Margin_%_per_sku                          Scenario  Revenue_Impact  \
0                   69.00  Scenario A : +10% Price Increase      -148831.94
1                   69.00  Scenario A : +10% Price Increase      -174472.74
2                   69.00  Scenario A : +10% Price Increase     -1111006.12
3                   68.00  Scenario A : +10% Price Increase       -99623.79
4                   68.00  Scenario A : +10% Price Increase       -79502.49
5                   68.00  Scenario A : +10% Price Increase      -555553.88

   Margin_Impact  New_Revenue  New_Units  New_Price
0     -102694.04   4501168.06   36084.40     124.74
1     -120386.19   5281527.26   47257.76     111.76
2     -766594.22  33608993.88  290986.96     115.50
3      -67744.18   3000376.21   24053.04     124.74
4      -54061.69   2400497.51   21479.04     111.76
5     -377776.64  16804446.12  145493.04     115.50

In [127]:
scenario_detail_df.to_excel('Elasticity_Detail.xlsx')

<ipython-input-127-667488138e81>:1: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.2.9' currently installed).
  scenario_detail_df.to_excel('Elasticity_Detail.xlsx')

In [128]:
scenario_total_df=pd.DataFrame(scenario_detail_df.groupby('Scenario')[['Revenue_Impact','Margin_Impact']].sum())

In [129]:
scenario_total_df

                                  Revenue_Impact  Margin_Impact
Scenario
Scenario A : +10% Price Increase     -7339818.94    -5025479.84
Scenario B : Status Quo                     0.00           0.00
Scenario C : -10% Price Decrease      1836221.60     1257230.91

In [130]:
scenario_total_df.to_excel('Elasticity_Total.xlsx')

<ipython-input-130-c241d8114389>:1: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.2.9' currently installed).
  scenario_total_df.to_excel('Elasticity_Total.xlsx')

In [131]:
scenario_market_df=pd.DataFrame(scenario_detail_df.groupby(['Scenario','Market'])['Revenue_Impact'].sum().reset_index())

In [132]:
scenario_sku_df=pd.DataFrame(scenario_detail_df.groupby(['Scenario','SKU'])['Revenue_Impact'].sum().reset_index())

In [133]:
scenario_market_df

                           Scenario Market  Revenue_Impact
0  Scenario A : +10% Price Increase    UAE      -992043.08
1  Scenario A : +10% Price Increase     UK      -792643.63
2  Scenario A : +10% Price Increase    USA     -5555132.24
3           Scenario B : Status Quo    UAE            0.00
4           Scenario B : Status Quo     UK            0.00
5           Scenario B : Status Quo    USA            0.00
6  Scenario C : -10% Price Decrease    UAE       247955.14
7  Scenario C : -10% Price Decrease     UK       199395.89
8  Scenario C : -10% Price Decrease    USA      1388870.56

In [134]:
scenario_market_df.to_excel('Elasticity_by_market.xlsx')

<ipython-input-134-1bd4029a97c6>:1: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.2.9' currently installed).
  scenario_market_df.to_excel('Elasticity_by_market.xlsx')

In [135]:
scenario_sku_df.sort_values(by=['Revenue_Impact'])

                            Scenario                      SKU  Revenue_Impact
4   Scenario A : +10% Price Increase               Vanilla 28     -2380012.63
3   Scenario A : +10% Price Increase   Oudgasm Tobacco Oud 04     -1489374.46
0   Scenario A : +10% Price Increase      Eden Juicy Apple 01     -1434310.81
5   Scenario A : +10% Price Increase  Yum Pistachio Gelato 33      -888798.51
1   Scenario A : +10% Price Increase   Freedom Musk Santal 34      -734680.16
2   Scenario A : +10% Price Increase                  Musk 12      -412642.38
11           Scenario B : Status Quo  Yum Pistachio Gelato 33            0.00
10           Scenario B : Status Quo               Vanilla 28            0.00
9            Scenario B : Status Quo   Oudgasm Tobacco Oud 04            0.00
8            Scenario B : Status Quo                  Musk 12            0.00
7            Scenario B : Status Quo   Freedom Musk Santal 34            0.00
6            Scenario B : Status Quo      Eden Juicy Apple 01            0.00
14  Scenario C : -10% Price Decrease                  Musk 12       103198.84
13  Scenario C : -10% Price Decrease   Freedom Musk Santal 34       182895.04
17  Scenario C : -10% Price Decrease  Yum Pistachio Gelato 33       222242.88
12  Scenario C : -10% Price Decrease      Eden Juicy Apple 01       358734.20
15  Scenario C : -10% Price Decrease   Oudgasm Tobacco Oud 04       373130.73
16  Scenario C : -10% Price Decrease               Vanilla 28       596019.91

In [136]:
scenario_sku_df.to_excel('Elasticity_by_SKU.xlsx')

<ipython-input-136-76c196efe63e>:1: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.2.9' currently installed).
  scenario_sku_df.to_excel('Elasticity_by_SKU.xlsx')

In [ ]:
## "Price elasticity modelling shows that a 10% price increase would reduce total Kayali revenue by $7.3M annually, with the US market absorbing 76% of that impact (-$5.6M) due to its dominant revenue base. Vanilla 28 alone accounts for $2.4M of the revenue loss under a price increase scenario — reinforcing its strategic importance as the brand's hero SKU. Conversely a 10% price reduction generates net positive revenue of $1.4M in the US market alone, suggesting Kayali's customer base is moderately price elastic and would respond strongly to targeted promotional pricing."